function report = compareWithPython(primaryInput, varargin)
% matlabv2native.compareWithPython Compare MATLAB-side native preview data against the Python oracle.

[sourceType, opts, invocation] = matlabv2native.internal.prepareInvocation( ...
    struct("Build", false, "OpenModel", false), ...
    primaryInput, ...
    varargin{:});

callerNames = evalin("caller", "who");
callerWorkspace = struct();
for index = 1:numel(callerNames)
    name = callerNames{index};
    if ~isvarname(name)
        continue;
    end
    try
        callerWorkspace.(name) = evalin("caller", name);
    catch
        % Ignore values that cannot be materialized deterministically.
    end
end

nativePreview = matlabv2native.internal.nativeAnalyze(sourceType, primaryInput, opts, callerWorkspace);
delegateOpts = matlabv2native.internal.applyNativePreview(opts, nativePreview);
delegateOpts = simucopilot.internal.enrichProblemMetadata(sourceType, primaryInput, delegateOpts, callerWorkspace);
request = simucopilot.internal.makeRequestStruct(sourceType, primaryInput, delegateOpts);
backendOut = simucopilot.internal.callBackend(request, delegateOpts);
parityReport = matlabv2native.internal.comparePreviewToProblem(nativePreview, backendOut);

report = struct( ...
    "Api", "matlabv2native", ...
    "BackendKind", "python_delegate", ...
    "SourceType", sourceType, ...
    "Invocation", invocation, ...
    "NativePreview", nativePreview, ...
    "PythonRoute", backendOut.Route, ...
    "PythonFirstOrder", backendOut.FirstOrder, ...
    "PythonNormalizedProblem", backendOut.NormalizedProblem, ...
    "ParityReport", parityReport ...
);
end
