function report = compareWithPython(primaryInput, varargin)
% matlabv2native.compareWithPython Compare MATLAB-side native preview metadata against the Python oracle.

analysis = matlabv2native.analyze(primaryInput, varargin{:});
report = struct( ...
    "Api", "matlabv2native", ...
    "BackendKind", analysis.BackendKind, ...
    "SourceType", analysis.SourceType, ...
    "NativePreview", analysis.NativePreview, ...
    "PythonRoute", analysis.Route, ...
    "PythonNormalizedProblem", analysis.NormalizedProblem, ...
    "ParityReport", analysis.ParityReport ...
);
end
