function defaults = backendDefaults()
% backendDefaults Return deterministic defaults for the MATLAB bridge.

internalRoot = fileparts(mfilename("fullpath"));
packageRoot = fileparts(fileparts(internalRoot));
matlabRoot = fileparts(packageRoot);
repoRoot = fileparts(matlabRoot);

pythonExecutable = getenv("SIMULINKCOPILOT_PYTHON");
if isempty(pythonExecutable)
    pythonExecutable = "python3";
end

defaults = struct( ...
    "RepoRoot", repoRoot, ...
    "PythonExecutable", char(pythonExecutable), ...
    "BackendEntryPoint", "pipeline.run_pipeline", ...
    "KeepTempFiles", false, ...
    "Verbose", false, ...
    "Build", false, ...
    "RunSim", true, ...
    "OpenModel", false, ...
    "ModelName", "", ...
    "TimeVariable", "t", ...
    "SimulinkOutputDir", "", ...
    "ClassificationMode", "", ...
    "SymbolConfig", struct(), ...
    "RuntimeOverride", struct(), ...
    "Assumptions", struct(), ...
    "DerivativeMap", struct(), ...
    "Tolerance", [] ...
);
end
