function [sourceType, opts, invocation, readout] = prepareInvocation(defaultOverrides, primaryInput, varargin)
% prepareInvocation Parse matlabv2native public options and infer the backend source type.

parser = inputParser;
parser.FunctionName = "matlabv2native.internal.prepareInvocation";
parser.KeepUnmatched = true;
addParameter(parser, "SourceType", "auto", @(value) ischar(value) || isstring(value));
addParameter(parser, "State", {}, @(value) localIsTextList(value));
addParameter(parser, "ParityMode", "runtime", @(value) ischar(value) || isstring(value));
parse(parser, varargin{:});

try
    sourceType = matlabv2native.internal.inferSourceType(primaryInput, parser.Results.SourceType);
catch exc
    readout = matlabv2native.internal.frontDoorSupport("build_readout", "unknown", primaryInput, struct());
    readout.Stages.source_type_validation = "failed";
    readout.UnderlyingErrorIdentifier = char(string(exc.identifier));
    readout.UnderlyingErrorMessage = char(string(exc.message));
    localRaisePrepareDiagnostic( ...
        "matlabv2native:FrontDoorSourceTypeValidationFailed", ...
        "source_type_validation", ...
        "The front door could not resolve a supported source type.", ...
        "matlabv2native could not classify the input into a supported source type before front-door validation.", ...
        exc.message, ...
        "Use MATLAB symbolic equations for the matlab_symbolic front door, or set SourceType explicitly to a supported value.", ...
        "unsupported", ...
        readout);
end

unmatched = parser.Unmatched;
if ~isempty(parser.Results.State)
    if isfield(unmatched, "States") && ~isempty(unmatched.States)
        readout = matlabv2native.internal.frontDoorSupport("build_readout", sourceType, primaryInput, struct());
        readout.Stages.option_validation = "failed";
        localRaisePrepareDiagnostic( ...
            "matlabv2native:FrontDoorConflictingStateOptions", ...
            "option_validation", ...
            "Use either State or States, not both.", ...
            "The front door does not allow both State and States in the same call because that makes the declared state order ambiguous.", ...
            "Both State and States were provided together.", ...
            "Pass exactly one of: 'State', 'x' or 'States', {'x','theta'}.", ...
            "unsupported", ...
            readout);
    end
    unmatched.States = parser.Results.State;
end

try
    parityMode = localNormalizeParityMode(parser.Results.ParityMode);
catch exc
    readout = matlabv2native.internal.frontDoorSupport("build_readout", sourceType, primaryInput, struct());
    readout.Stages.option_validation = "failed";
    readout.UnderlyingErrorIdentifier = char(string(exc.identifier));
    readout.UnderlyingErrorMessage = char(string(exc.message));
    localRaisePrepareDiagnostic( ...
        "matlabv2native:FrontDoorInvalidParityMode", ...
        "option_validation", ...
        "ParityMode is invalid.", ...
        "The front door only accepts deterministic runtime mode or explicit Python parity mode.", ...
        exc.message, ...
        "Use ParityMode 'runtime' or 'python'.", ...
        "unsupported", ...
        readout);
end

nameValueArgs = localStructToNameValue(unmatched);
try
    opts = simucopilot.internal.validateOptions(defaultOverrides, nameValueArgs{:});
catch exc
    readout = matlabv2native.internal.frontDoorSupport("build_readout", sourceType, primaryInput, struct());
    readout.Stages.option_validation = "failed";
    readout.UnderlyingErrorIdentifier = char(string(exc.identifier));
    readout.UnderlyingErrorMessage = char(string(exc.message));
    localRaisePrepareDiagnostic( ...
        "matlabv2native:FrontDoorInvalidOptions", ...
        "option_validation", ...
        "The provided options are invalid for this front door.", ...
        "Shared option validation rejected one or more name/value arguments before native route analysis began.", ...
        exc.message, ...
        "Fix the named option in the error details and retry. For matlab_symbolic, always pass an explicit State / States declaration.", ...
        "unsupported", ...
        readout);
end

readout = matlabv2native.internal.frontDoorSupport("build_readout", sourceType, primaryInput, opts);
[opts, readout] = matlabv2native.internal.frontDoorSupport("validate_contract", sourceType, opts, readout);
invocation = struct( ...
    "RequestedSourceType", char(string(parser.Results.SourceType)), ...
    "ResolvedSourceType", sourceType, ...
    "ParityMode", parityMode ...
);
end

function tf = localIsTextList(value)
tf = isempty(value) || ischar(value) || isstring(value) || iscellstr(value);
if tf && iscell(value)
    tf = all(cellfun(@(item) ischar(item) || isstring(item), value));
end
end

function nv = localStructToNameValue(values)
fields = fieldnames(values);
nv = cell(1, numel(fields) * 2);
for index = 1:numel(fields)
    nv{2 * index - 1} = fields{index};
    nv{2 * index} = values.(fields{index});
end
end

function mode = localNormalizeParityMode(raw)
mode = lower(strtrim(char(string(raw))));
switch mode
    case {"runtime", "native", "off"}
        mode = "runtime";
    case {"python", "parity", "compare", "on"}
        mode = "python";
    otherwise
        error("matlabv2native:InvalidParityMode", ...
            "ParityMode must be 'runtime' or 'python'.");
end

function localRaisePrepareDiagnostic(code, stage, summary, details, likelyCause, suggestedFix, supportStatus, readout)
diagnostic = struct( ...
    "Code", char(string(code)), ...
    "Stage", char(string(stage)), ...
    "Summary", char(string(summary)), ...
    "Details", char(string(details)), ...
    "LikelyCause", char(string(likelyCause)), ...
    "SuggestedFix", char(string(suggestedFix)), ...
    "SupportStatus", char(string(supportStatus)), ...
    "RepresentationKind", char(string(localStructScalar(readout, "RepresentationKind", ""))), ...
    "DeclaredStates", localStructScalar(readout, "DeclaredStates", {}), ...
    "BoundStates", localStructScalar(readout, "BoundStates", {}), ...
    "ScalarizedEquationCount", double(localStructScalar(readout, "ScalarizedEquationCount", 0)), ...
    "Route", char(string(localStructScalar(readout, "Route", ""))), ...
    "RouteStatus", char(string(localStructScalar(readout, "RouteStatus", ""))), ...
    "FallbackUsed", logical(localStructScalar(readout, "FallbackUsed", false)), ...
    "Delegated", logical(localStructScalar(readout, "Delegated", false)), ...
    "UnderlyingErrorIdentifier", char(string(localStructScalar(readout, "UnderlyingErrorIdentifier", ""))), ...
    "UnderlyingErrorMessage", char(string(localStructScalar(readout, "UnderlyingErrorMessage", ""))), ...
    "Readout", readout ...
);
matlabv2native.internal.frontDoorSupport("raise", diagnostic);
end

function value = localStructScalar(container, fieldName, defaultValue)
if isstruct(container) && isfield(container, fieldName)
    value = container.(fieldName);
    return;
end
value = defaultValue;
end
end
